In [5]:
import nltk
nltk.download('punkt_tab')


from nltk.tokenize import word_tokenize,sent_tokenize
text = 'this is first sentence.this is second sentence '
w = word_tokenize(text)
print(w)

s = sent_tokenize(text)
s

['this', 'is', 'first', 'sentence.this', 'is', 'second', 'sentence']


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


['this is first sentence.this is second sentence']

In [6]:
from nltk import pos_tag
p = pos_tag(w)
print(p)

LookupError: 
**********************************************************************
  Resource averaged_perceptron_tagger_eng not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger_eng')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load taggers/averaged_perceptron_tagger_eng/

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


In [7]:
import nltk
from nltk import word_tokenize,pos_tag,ne_chunk
text = 'apple is a hong kong factory of $6 million'

new = ne_chunk(pos_tag(word_tokenize(text)))
print(new)

LookupError: 
**********************************************************************
  Resource averaged_perceptron_tagger_eng not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger_eng')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load taggers/averaged_perceptron_tagger_eng/

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


In [ ]:
# 4) removing stopwords and punctuation

text = 'this is nlp. this is python'
from string import punctuation
from nltk.corpus import stopwords
stop = stopwords.words("english")

sw_list = list(punctuation) + stop

def text_cleaner(text):
    filtered_text = []
    from nltk.tokenize import word_tokenize
    tokenize = word_tokenize(text)  # tokenize
    for word in tokenize:
        if word.lower() not in sw_list:
            filtered_text.append(word)

    return " ".join(filtered_text)
    # return filtered_text

# calling the function
text_cleaner(text)

In [ ]:
# 5) stemming

from nltk.stem import SnowballStemmer
s = SnowballStemmer("english")
s.stem("history")

'histori'

# stemming on a text

text = "this is nlp. this is python"

# 1. tokenize
from nltk.tokenize import word_tokenize
tokenize = word_tokenize(text)

# 2. stemming
from nltk.stem import SnowballStemmer
s = SnowballStemmer("english")

# 3. looping
for i in tokenize:
    print(s.stem(i))

In [8]:
# 7) cv/bow

import numpy as np
import pandas as pd
df = pd.DataFrame({'text':['people watch campus', 'campus watch campus',
                           'people write comment', 'campus write comment']})

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()  # ngram_range=(2,2): use this hyperparameter for ngram
bow = cv.fit_transform(df['text']).toarray()

print(bow)
print(bow[0])
print(bow[1])

# vocabulary / unique words
print(cv.vocabulary_)

[[1 0 1 1 0]
 [2 0 0 1 0]
 [0 1 1 0 1]
 [1 1 0 0 1]]
[1 0 1 1 0]
[2 0 0 1 0]
{'people': 2, 'watch': 3, 'campus': 0, 'write': 4, 'comment': 1}


In [ ]:
# 1) Importing libraries

import pandas as pd
temp_df = pd.read_csv("IMDB Dataset.xls")
temp_df.shape

In [ ]:
df = temp_df.iloc[:1000]
df.shape

In [ ]:
df["sentiment"].value_counts()

In [ ]:
df.isnull().sum()

In [ ]:
df.duplicated().sum()

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

In [ ]:
from string import punctuation
from nltk.corpus import stopwords
stop = stopwords.words("english")

sw_list = list(punctuation) + stop

In [ ]:
def text_cleaner(text):
    filtered_text = []
    from nltk.tokenize import word_tokenize
    tokenize = word_tokenize(text)
    for word in tokenize:
        if word.lower() not in sw_list:
            filtered_text.append(word)
    return " ".join(filtered_text)

In [ ]:
df['review'] = df['review'].apply(text_cleaner)

In [ ]:
# differentiating
X = df.iloc[:,0:1]
y = df['sentiment']


In [ ]:
# encoding
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [ ]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
# 5) feature extraction (bow)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=3000)
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()


# Note:
#     if x and y ko differentiation krte time iloc ka use kiya hai.
#     then use X_train['review'] and X_test['review'] this in feature extraction

#     but if we have use simple X = ['review'] without using iloc.
#     then use "X_train", "X_test" in features extraction.

In [ ]:
# Naive Bayes
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train_bow,y_train)   # fitting training data

In [ ]:
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_pred))

confusion_matrix(y_test,y_pred)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred  = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

In [ ]:
from sklearn.svm import SVC

# Initialize the SVM model
svm_model = SVC(kernel='linear')  # You can use different kernels like 'rbf', 'poly', etc.
svm_model.fit(X_train_bow, y_train)  # Train the model

# Predict using the SVM model
y_pred_svm = svm_model.predict(X_test_bow)

# Evaluate the SVM model
print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print("SVM Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))


In [ ]:
import pandas as pd
df = pd.read_csv("smsspamcollection.tsv", sep='\t')
df.head(1)